import type React from 'react';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import type { CardRef, GameAction, LegalAction } from '@dune/shared';
import { GameApi } from '../api/GameApi';
import { useSession } from '../state/SessionContext';
import { ActionPanel, BoardMap, ConflictPanel, GameLog, ImperiumRow, IntrigueHand, OpponentPanel, PlayerHand, ResourceBar } from '../components/GameParts';
import { Panel } from '../components/UI';

export function GameView(): React.ReactElement { const { id = '' } = useParams(); const navigate = useNavigate(); const session = useSession(); const [selected, setSelected] = useState<CardRef | null>(null); const [error, setError] = useState('');
  useEffect(() => { let stop: (() => void) | undefined; GameApi.getState(id).then(session.setGame).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load game.')); stop = GameApi.subscribe(id, session.handleMessage, session.setConnected); return () => stop?.(); }, [id, session.setGame, session.handleMessage, session.setConnected]);
  useEffect(() => { if (session.game?.ended) navigate(`/game/${id}/end`); }, [id, navigate, session.game?.ended]);
  const state = session.game; const me = state?.players.find((player) => player.playerId === session.playerId); const actions = state?.legalActions ?? [];
  const legalSpaces = useMemo(() => selected ? actions.filter((action): action is Extract<LegalAction, { kind: 'sendAgent' }> => action.kind === 'sendAgent' && action.card.cardId === selected.cardId).map((action) => action.spaceId) : [], [actions, selected]);
  async function act(action: GameAction): Promise<void> { try { setError(''); const result = await GameApi.sendAction(id, action); if (result.accepted) { session.setGame(result.state); setSelected(null); } else setError(result.reason); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Action failed.'); } }
  if (!state || !me) return <main className="shell"><Panel title="Entering the Imperium"><p>{error || 'Loading game…'}</p></Panel></main>;
  return <main className="game-shell"><header className="topbar game-topbar"><div><p className="eyebrow">Dune Imperium · Round {state.roundNumber}</p><h1>{state.phase === 'playerTurns' ? 'Agent turns' : state.phase}</h1></div><div className="turn-meta"><span className={session.connected ? 'connection online' : 'connection'}>{session.connected ? '● Connected' : '○ Reconnecting'}</span><span>First Player: {state.players.find((player) => player.playerId === state.firstPlayerId)?.name ?? '—'}</span></div></header><ResourceBar player={me} />{error && <button className="toast error" onClick={() => setError('')} role="alert">{error} ×</button>}<div className="game-layout"><aside className="left-rail"><ConflictPanel state={state} /><OpponentPanel players={state.players} me={me.playerId} /><GameLog state={state} /></aside><section className="board-column"><BoardMap state={state} selectedCard={selected} legalSpaces={legalSpaces} onSpace={(spaceId) => selected && void act({ kind: 'sendAgent', cardId: selected.cardId, spaceId })} /><ImperiumRow state={state} actions={actions} onAcquire={(cardKey) => void act({ kind: 'acquireCard', cardKey })}/><PlayerHand cards={me.hand ?? []} actions={actions} onPlay={(card) => setSelected(card)} /><IntrigueHand player={me} actions={actions} onPlay={(intrigueId) => void act({ kind: 'playIntrigue', intrigueId })}/></section><aside className="right-rail"><ActionPanel state={state} me={me} selectedCard={selected} onAction={(action) => void act(action)} /><Panel title="Influence tracks"><div className="influence-list">{Object.entries(me.influence).map(([faction, score]) => <div key={faction}><span>{faction}</span><strong>{score}</strong></div>)}</div></Panel><Panel title="Reveal"><p>{state.reveal.revealed ? `${state.reveal.revealed.length} cards revealed` : 'Reveal details appear here.'}</p>{state.reveal.pendingPersuasion !== null && <p>{state.reveal.pendingPersuasion} persuasion available</p>}</Panel></aside></div></main>;
}
