import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import type { GameState } from '@dune/shared';
import { GameView } from './GameView';
import { SessionProvider } from '../state/SessionContext';
import { GameApi } from '../api/GameApi';

const state = { gameId: 'g', lobbyCode: 'ABCD', roundNumber: 1, phase: 'playerTurns', currentPlayerId: 'p', firstPlayerId: 'p', viewForPlayerId: 'p', board: [{ id: 'arrakeen', name: 'Arrakeen', icon: 'emperor', cost: null, requirementText: null, occupantPlayerId: null, controllerPlayerId: null, bonusSpice: 0 }], imperiumRow: [], reserve: { arrakisLiaison: { cardKey: 'liaison', count: 1 }, spiceMustFlow: { cardKey: 'spice', count: 1 }, foldspace: { cardKey: 'fold', count: 1 } }, conflict: { card: null }, reveal: { revealed: null, pendingPersuasion: null, combatStrengthPreview: null }, combat: null, players: [{ playerId: 'p', name: 'Paul', color: 'red', leader: { cardId: 'l', cardKey: 'leader' }, score: 1, combatStrength: 0, resources: { solari: 0, spice: 0, water: 1, persuasion: 0 }, troopsInSupply: 9, troopsInGarrison: 2, troopsInConflict: 0, influence: { emperor: 0, spacingGuild: 0, beneGesserit: 0, fremen: 0 }, alliances: [], hand: [{ cardId: 'c', cardKey: 'card' }], handCount: 1, deckCount: 0, discardCount: 0, intrigueCards: [], intrigueCount: 0, agentsRemaining: 2, agentsOnBoard: 0, hasMentat: false }], legalActions: [{ kind: 'playCard', card: { cardId: 'c', cardKey: 'card' } }, { kind: 'sendAgent', card: { cardId: 'c', cardKey: 'card' }, spaceId: 'arrakeen' }], log: [], ended: false, winnerId: null } as GameState;
describe('GameView', () => { it('shows only server-legal cards and sends the selected space', async () => { vi.spyOn(GameApi, 'getState').mockResolvedValue(state); vi.spyOn(GameApi, 'subscribe').mockReturnValue(() => undefined); vi.spyOn(GameApi, 'sendAction').mockResolvedValue({ accepted: true, actionId: 'a', state }); render(<SessionProvider initialPlayerId="p"><MemoryRouter initialEntries={['/game/g']}><Routes><Route path="/game/:id" element={<GameView />} /></Routes></MemoryRouter></SessionProvider>); expect(await screen.findByText('card')).toBeInTheDocument(); fireEvent.click(screen.getByText('card')); expect(screen.getByRole('button', { name: /Arrakeen/ })).toBeEnabled(); fireEvent.click(screen.getByRole('button', { name: /Arrakeen/ })); expect(GameApi.sendAction).toHaveBeenCalledWith('g', { kind: 'sendAgent', cardId: 'c', spaceId: 'arrakeen' }); }); });
